
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\hallo\OneDrive\Desktop\SP2025 DOCS\MIS161\GUI\rebuild\invoice\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=0.0,
    y=0.0,
    width=240.0,
    height=120.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=240.0,
    y=0.0,
    width=240.0,
    height=120.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=480.0,
    y=0.0,
    width=240.0,
    height=120.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=720.0,
    y=0.0,
    width=240.0,
    height=120.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=960.0,
    y=0.0,
    width=240.0,
    height=120.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=1200.0,
    y=0.0,
    width=240.0,
    height=120.0
)

canvas.create_rectangle(
    68.0,
    152.0,
    167.0,
    203.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    379.0,
    152.0,
    478.0,
    203.0,
    fill="#D9D9D9",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    272.5,
    177.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=170.0,
    y=152.0,
    width=205.0,
    height=49.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    585.5,
    177.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=482.0,
    y=152.0,
    width=207.0,
    height=49.0
)

canvas.create_rectangle(
    68.0,
    210.0,
    167.0,
    262.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    379.0,
    209.0,
    478.0,
    260.0,
    fill="#D9D9D9",
    outline="")

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    272.5,
    234.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=170.0,
    y=209.0,
    width=205.0,
    height=49.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    585.5,
    234.5,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=482.0,
    y=209.0,
    width=207.0,
    height=49.0
)

canvas.create_rectangle(
    68.0,
    267.0,
    167.0,
    318.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    68.0,
    325.0,
    170.0,
    376.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    81.0,
    276.0,
    anchor="nw",
    text="Client Email",
    fill="#000000",
    font=("MerriweatherSans Bold", 11 * -1)
)

canvas.create_rectangle(
    379.0,
    267.0,
    478.0,
    318.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    267.0,
    325.0,
    371.0,
    376.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    474.0,
    325.0,
    576.0,
    376.0,
    fill="#D9D9D9",
    outline="")

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    272.5,
    292.5,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=170.0,
    y=267.0,
    width=205.0,
    height=49.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    218.0,
    350.5,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=169.0,
    y=325.0,
    width=98.0,
    height=49.0
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    423.5,
    350.5,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=371.0,
    y=325.0,
    width=105.0,
    height=49.0
)

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    632.5,
    350.5,
    image=entry_image_8
)
entry_8 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_8.place(
    x=576.0,
    y=325.0,
    width=113.0,
    height=49.0
)

entry_image_9 = PhotoImage(
    file=relative_to_assets("entry_9.png"))
entry_bg_9 = canvas.create_image(
    585.5,
    292.5,
    image=entry_image_9
)
entry_9 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_9.place(
    x=482.0,
    y=267.0,
    width=207.0,
    height=49.0
)

canvas.create_text(
    82.0,
    161.0,
    anchor="nw",
    text="Client Name",
    fill="#000000",
    font=("MerriweatherSans Bold", 11 * -1)
)

canvas.create_text(
    388.0,
    161.0,
    anchor="nw",
    text="Order Number",
    fill="#000000",
    font=("MerriweatherSans Bold", 11 * -1)
)

canvas.create_text(
    81.0,
    217.0,
    anchor="nw",
    text="Client Phone",
    fill="#000000",
    font=("MerriweatherSans Bold", 11 * -1)
)

canvas.create_text(
    389.0,
    276.0,
    anchor="nw",
    text="Drop Off Date",
    fill="#000000",
    font=("MerriweatherSans Bold", 11 * -1)
)

canvas.create_text(
    394.0,
    217.0,
    anchor="nw",
    text="Received By",
    fill="#000000",
    font=("MerriweatherSans Bold", 11 * -1)
)

canvas.create_text(
    69.0,
    337.0,
    anchor="nw",
    text="Expected Finish Date",
    fill="#000000",
    font=("MerriweatherSans Bold", 11 * -1)
)

canvas.create_text(
    287.0,
    334.0,
    anchor="nw",
    text="Finish Date",
    fill="#000000",
    font=("MerriweatherSans Bold", 11 * -1)
)

canvas.create_text(
    492.0,
    334.0,
    anchor="nw",
    text="Pick Up Date",
    fill="#000000",
    font=("MerriweatherSans Bold", 11 * -1)
)

canvas.create_rectangle(
    66.0,
    413.0,
    282.0,
    485.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    66.0,
    486.0,
    282.0,
    558.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    66.0,
    558.0,
    282.0,
    630.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    66.0,
    625.0,
    282.0,
    697.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    66.0,
    697.0,
    282.0,
    769.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    66.0,
    769.0,
    282.0,
    841.0,
    fill="#D9D9D9",
    outline="")

entry_image_10 = PhotoImage(
    file=relative_to_assets("entry_10.png"))
entry_bg_10 = canvas.create_image(
    490.5,
    449.0,
    image=entry_image_10
)
entry_10 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_10.place(
    x=292.0,
    y=413.0,
    width=397.0,
    height=70.0
)

entry_image_11 = PhotoImage(
    file=relative_to_assets("entry_11.png"))
entry_bg_11 = canvas.create_image(
    490.5,
    522.0,
    image=entry_image_11
)
entry_11 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_11.place(
    x=292.0,
    y=486.0,
    width=397.0,
    height=70.0
)

entry_image_12 = PhotoImage(
    file=relative_to_assets("entry_12.png"))
entry_bg_12 = canvas.create_image(
    490.5,
    594.0,
    image=entry_image_12
)
entry_12 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_12.place(
    x=292.0,
    y=558.0,
    width=397.0,
    height=70.0
)

entry_image_13 = PhotoImage(
    file=relative_to_assets("entry_13.png"))
entry_bg_13 = canvas.create_image(
    490.5,
    661.0,
    image=entry_image_13
)
entry_13 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_13.place(
    x=292.0,
    y=625.0,
    width=397.0,
    height=70.0
)

entry_image_14 = PhotoImage(
    file=relative_to_assets("entry_14.png"))
entry_bg_14 = canvas.create_image(
    490.5,
    732.0,
    image=entry_image_14
)
entry_14 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_14.place(
    x=292.0,
    y=696.0,
    width=397.0,
    height=70.0
)

canvas.create_rectangle(
    292.0,
    769.0,
    689.0,
    841.0,
    fill="#F3F3F3",
    outline="")

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=502.0,
    y=904.0,
    width=195.0,
    height=72.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=741.0,
    y=904.0,
    width=195.0,
    height=72.0
)

entry_image_15 = PhotoImage(
    file=relative_to_assets("entry_15.png"))
entry_bg_15 = canvas.create_image(
    490.5,
    805.0,
    image=entry_image_15
)
entry_15 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_15.place(
    x=292.0,
    y=769.0,
    width=397.0,
    height=70.0
)

canvas.create_text(
    66.0,
    437.0,
    anchor="nw",
    text="Gun(s) Manufacturers, Model, S/N and Condition",
    fill="#000000",
    font=("MergeOne Regular", 13 * -1)
)

canvas.create_text(
    76.0,
    502.0,
    anchor="nw",
    text="When and where was gun purchased\n",
    fill="#000000",
    font=("MergeOne Regular", 13 * -1)
)

canvas.create_text(
    68.0,
    578.0,
    anchor="nw",
    text="List any previous upgrades or repairs\n",
    fill="#000000",
    font=("MergeOne Regular", 13 * -1)
)

canvas.create_text(
    96.0,
    646.0,
    anchor="nw",
    text="All parts and extras left\n",
    fill="#000000",
    font=("MergeOne Regular", 13 * -1)
)

canvas.create_text(
    96.0,
    719.0,
    anchor="nw",
    text="Work Description\n",
    fill="#000000",
    font=("MergeOne Regular", 13 * -1)
)

canvas.create_text(
    104.0,
    795.0,
    anchor="nw",
    text="Additional Comments",
    fill="#000000",
    font=("MergeOne Regular", 13 * -1)
)

canvas.create_rectangle(
    784.0,
    148.0,
    1057.0,
    170.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    866.0,
    153.0,
    anchor="nw",
    text="Labor Description",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_rectangle(
    1057.0,
    148.0,
    1163.0,
    170.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    1057.0,
    236.0,
    1163.0,
    258.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    1163.0,
    236.0,
    1269.0,
    258.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    1269.0,
    236.0,
    1375.0,
    258.0,
    fill="#D9D9D9",
    outline="")

entry_image_16 = PhotoImage(
    file=relative_to_assets("entry_16.png"))
entry_bg_16 = canvas.create_image(
    1110.0,
    181.0,
    image=entry_image_16
)
entry_16 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_16.place(
    x=1057.0,
    y=170.0,
    width=106.0,
    height=20.0
)

entry_image_17 = PhotoImage(
    file=relative_to_assets("entry_17.png"))
entry_bg_17 = canvas.create_image(
    1110.0,
    203.0,
    image=entry_image_17
)
entry_17 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_17.place(
    x=1057.0,
    y=192.0,
    width=106.0,
    height=20.0
)

entry_image_18 = PhotoImage(
    file=relative_to_assets("entry_18.png"))
entry_bg_18 = canvas.create_image(
    1110.0,
    225.0,
    image=entry_image_18
)
entry_18 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_18.place(
    x=1057.0,
    y=214.0,
    width=106.0,
    height=20.0
)

entry_image_19 = PhotoImage(
    file=relative_to_assets("entry_19.png"))
entry_bg_19 = canvas.create_image(
    1216.0,
    225.0,
    image=entry_image_19
)
entry_19 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_19.place(
    x=1163.0,
    y=214.0,
    width=106.0,
    height=20.0
)

entry_image_20 = PhotoImage(
    file=relative_to_assets("entry_20.png"))
entry_bg_20 = canvas.create_image(
    1216.0,
    203.0,
    image=entry_image_20
)
entry_20 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_20.place(
    x=1163.0,
    y=192.0,
    width=106.0,
    height=20.0
)

entry_image_21 = PhotoImage(
    file=relative_to_assets("entry_21.png"))
entry_bg_21 = canvas.create_image(
    1216.0,
    181.0,
    image=entry_image_21
)
entry_21 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_21.place(
    x=1163.0,
    y=170.0,
    width=106.0,
    height=20.0
)

entry_image_22 = PhotoImage(
    file=relative_to_assets("entry_22.png"))
entry_bg_22 = canvas.create_image(
    1322.0,
    181.0,
    image=entry_image_22
)
entry_22 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_22.place(
    x=1269.0,
    y=170.0,
    width=106.0,
    height=20.0
)

entry_image_23 = PhotoImage(
    file=relative_to_assets("entry_23.png"))
entry_bg_23 = canvas.create_image(
    1322.0,
    203.0,
    image=entry_image_23
)
entry_23 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_23.place(
    x=1269.0,
    y=192.0,
    width=106.0,
    height=20.0
)

entry_image_24 = PhotoImage(
    file=relative_to_assets("entry_24.png"))
entry_bg_24 = canvas.create_image(
    1322.0,
    225.0,
    image=entry_image_24
)
entry_24 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_24.place(
    x=1269.0,
    y=214.0,
    width=106.0,
    height=20.0
)

canvas.create_rectangle(
    1163.0,
    148.0,
    1269.0,
    170.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    1269.0,
    148.0,
    1375.0,
    170.0,
    fill="#D9D9D9",
    outline="")

entry_image_25 = PhotoImage(
    file=relative_to_assets("entry_25.png"))
entry_bg_25 = canvas.create_image(
    920.5,
    181.0,
    image=entry_image_25
)
entry_25 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_25.place(
    x=784.0,
    y=170.0,
    width=273.0,
    height=20.0
)

entry_image_26 = PhotoImage(
    file=relative_to_assets("entry_26.png"))
entry_bg_26 = canvas.create_image(
    920.5,
    203.0,
    image=entry_image_26
)
entry_26 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_26.place(
    x=784.0,
    y=192.0,
    width=273.0,
    height=20.0
)

entry_image_27 = PhotoImage(
    file=relative_to_assets("entry_27.png"))
entry_bg_27 = canvas.create_image(
    920.5,
    225.0,
    image=entry_image_27
)
entry_27 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_27.place(
    x=784.0,
    y=214.0,
    width=273.0,
    height=20.0
)

entry_image_28 = PhotoImage(
    file=relative_to_assets("entry_28.png"))
entry_bg_28 = canvas.create_image(
    1110.0,
    296.0,
    image=entry_image_28
)
entry_28 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_28.place(
    x=1057.0,
    y=285.0,
    width=106.0,
    height=20.0
)

entry_image_29 = PhotoImage(
    file=relative_to_assets("entry_29.png"))
entry_bg_29 = canvas.create_image(
    1110.0,
    318.0,
    image=entry_image_29
)
entry_29 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_29.place(
    x=1057.0,
    y=307.0,
    width=106.0,
    height=20.0
)

entry_image_30 = PhotoImage(
    file=relative_to_assets("entry_30.png"))
entry_bg_30 = canvas.create_image(
    1110.0,
    340.0,
    image=entry_image_30
)
entry_30 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_30.place(
    x=1057.0,
    y=329.0,
    width=106.0,
    height=20.0
)

entry_image_31 = PhotoImage(
    file=relative_to_assets("entry_31.png"))
entry_bg_31 = canvas.create_image(
    1110.0,
    362.0,
    image=entry_image_31
)
entry_31 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_31.place(
    x=1057.0,
    y=351.0,
    width=106.0,
    height=20.0
)

entry_image_32 = PhotoImage(
    file=relative_to_assets("entry_32.png"))
entry_bg_32 = canvas.create_image(
    1110.0,
    384.0,
    image=entry_image_32
)
entry_32 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_32.place(
    x=1057.0,
    y=373.0,
    width=106.0,
    height=20.0
)

entry_image_33 = PhotoImage(
    file=relative_to_assets("entry_33.png"))
entry_bg_33 = canvas.create_image(
    1216.0,
    384.0,
    image=entry_image_33
)
entry_33 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_33.place(
    x=1163.0,
    y=373.0,
    width=106.0,
    height=20.0
)

entry_image_34 = PhotoImage(
    file=relative_to_assets("entry_34.png"))
entry_bg_34 = canvas.create_image(
    1216.0,
    362.0,
    image=entry_image_34
)
entry_34 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_34.place(
    x=1163.0,
    y=351.0,
    width=106.0,
    height=20.0
)

entry_image_35 = PhotoImage(
    file=relative_to_assets("entry_35.png"))
entry_bg_35 = canvas.create_image(
    1216.0,
    340.0,
    image=entry_image_35
)
entry_35 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_35.place(
    x=1163.0,
    y=329.0,
    width=106.0,
    height=20.0
)

entry_image_36 = PhotoImage(
    file=relative_to_assets("entry_36.png"))
entry_bg_36 = canvas.create_image(
    1216.0,
    318.0,
    image=entry_image_36
)
entry_36 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_36.place(
    x=1163.0,
    y=307.0,
    width=106.0,
    height=20.0
)

entry_image_37 = PhotoImage(
    file=relative_to_assets("entry_37.png"))
entry_bg_37 = canvas.create_image(
    1216.0,
    296.0,
    image=entry_image_37
)
entry_37 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_37.place(
    x=1163.0,
    y=285.0,
    width=106.0,
    height=20.0
)

entry_image_38 = PhotoImage(
    file=relative_to_assets("entry_38.png"))
entry_bg_38 = canvas.create_image(
    1322.0,
    296.0,
    image=entry_image_38
)
entry_38 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_38.place(
    x=1269.0,
    y=285.0,
    width=106.0,
    height=20.0
)

entry_image_39 = PhotoImage(
    file=relative_to_assets("entry_39.png"))
entry_bg_39 = canvas.create_image(
    1322.0,
    318.0,
    image=entry_image_39
)
entry_39 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_39.place(
    x=1269.0,
    y=307.0,
    width=106.0,
    height=20.0
)

entry_image_40 = PhotoImage(
    file=relative_to_assets("entry_40.png"))
entry_bg_40 = canvas.create_image(
    1322.0,
    340.0,
    image=entry_image_40
)
entry_40 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_40.place(
    x=1269.0,
    y=329.0,
    width=106.0,
    height=20.0
)

entry_image_41 = PhotoImage(
    file=relative_to_assets("entry_41.png"))
entry_bg_41 = canvas.create_image(
    1322.0,
    362.0,
    image=entry_image_41
)
entry_41 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_41.place(
    x=1269.0,
    y=351.0,
    width=106.0,
    height=20.0
)

entry_image_42 = PhotoImage(
    file=relative_to_assets("entry_42.png"))
entry_bg_42 = canvas.create_image(
    1322.0,
    384.0,
    image=entry_image_42
)
entry_42 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_42.place(
    x=1269.0,
    y=373.0,
    width=106.0,
    height=20.0
)

entry_image_43 = PhotoImage(
    file=relative_to_assets("entry_43.png"))
entry_bg_43 = canvas.create_image(
    920.5,
    296.0,
    image=entry_image_43
)
entry_43 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_43.place(
    x=784.0,
    y=285.0,
    width=273.0,
    height=20.0
)

entry_image_44 = PhotoImage(
    file=relative_to_assets("entry_44.png"))
entry_bg_44 = canvas.create_image(
    920.5,
    318.0,
    image=entry_image_44
)
entry_44 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_44.place(
    x=784.0,
    y=307.0,
    width=273.0,
    height=20.0
)

entry_image_45 = PhotoImage(
    file=relative_to_assets("entry_45.png"))
entry_bg_45 = canvas.create_image(
    920.5,
    340.0,
    image=entry_image_45
)
entry_45 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_45.place(
    x=784.0,
    y=329.0,
    width=273.0,
    height=20.0
)

entry_image_46 = PhotoImage(
    file=relative_to_assets("entry_46.png"))
entry_bg_46 = canvas.create_image(
    920.5,
    362.0,
    image=entry_image_46
)
entry_46 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_46.place(
    x=784.0,
    y=351.0,
    width=273.0,
    height=20.0
)

entry_image_47 = PhotoImage(
    file=relative_to_assets("entry_47.png"))
entry_bg_47 = canvas.create_image(
    920.5,
    384.0,
    image=entry_image_47
)
entry_47 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_47.place(
    x=784.0,
    y=373.0,
    width=273.0,
    height=20.0
)

canvas.create_rectangle(
    784.0,
    236.0,
    1057.0,
    258.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    1057.0,
    153.0,
    anchor="nw",
    text="Hours",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_text(
    1161.0,
    153.0,
    anchor="nw",
    text="Rate",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_text(
    1158.0,
    241.0,
    anchor="nw",
    text="Labor Total",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_text(
    1267.0,
    153.0,
    anchor="nw",
    text="Amount",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_rectangle(
    784.0,
    263.0,
    1057.0,
    285.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    866.0,
    268.0,
    anchor="nw",
    text="Material Description",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_rectangle(
    1057.0,
    263.0,
    1163.0,
    285.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    1163.0,
    263.0,
    1269.0,
    285.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    1269.0,
    263.0,
    1375.0,
    285.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    1057.0,
    268.0,
    anchor="nw",
    text="Quantity",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_text(
    1161.0,
    268.0,
    anchor="nw",
    text="Price Per Unit",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_text(
    1267.0,
    268.0,
    anchor="nw",
    text="Amount",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_rectangle(
    784.0,
    395.0,
    1057.0,
    417.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    1057.0,
    395.0,
    1163.0,
    417.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    1163.0,
    395.0,
    1269.0,
    417.0,
    fill="#D9D9D9",
    outline="")

entry_image_48 = PhotoImage(
    file=relative_to_assets("entry_48.png"))
entry_bg_48 = canvas.create_image(
    1322.0,
    406.0,
    image=entry_image_48
)
entry_48 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_48.place(
    x=1269.0,
    y=395.0,
    width=106.0,
    height=20.0
)

canvas.create_text(
    1161.0,
    400.0,
    anchor="nw",
    text="Material Total",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_rectangle(
    784.0,
    440.0,
    940.0,
    474.0,
    fill="#D9D9D9",
    outline="")

entry_image_49 = PhotoImage(
    file=relative_to_assets("entry_49.png"))
entry_bg_49 = canvas.create_image(
    1017.5,
    457.0,
    image=entry_image_49
)
entry_49 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_49.place(
    x=940.0,
    y=440.0,
    width=155.0,
    height=32.0
)

canvas.create_rectangle(
    784.0,
    484.0,
    940.0,
    518.0,
    fill="#D9D9D9",
    outline="")

entry_image_50 = PhotoImage(
    file=relative_to_assets("entry_50.png"))
entry_bg_50 = canvas.create_image(
    1017.5,
    501.0,
    image=entry_image_50
)
entry_50 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_50.place(
    x=940.0,
    y=484.0,
    width=155.0,
    height=32.0
)

canvas.create_text(
    812.0,
    450.0,
    anchor="nw",
    text="Work Completed By",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_text(
    805.0,
    494.0,
    anchor="nw",
    text="Approving Party Name",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_rectangle(
    784.0,
    518.0,
    940.0,
    552.0,
    fill="#D9D9D9",
    outline="")

entry_image_51 = PhotoImage(
    file=relative_to_assets("entry_51.png"))
entry_bg_51 = canvas.create_image(
    1017.5,
    535.0,
    image=entry_image_51
)
entry_51 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_51.place(
    x=940.0,
    y=518.0,
    width=155.0,
    height=32.0
)

canvas.create_text(
    796.0,
    528.0,
    anchor="nw",
    text="Approving Party Signature",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_rectangle(
    784.0,
    552.0,
    940.0,
    586.0,
    fill="#D9D9D9",
    outline="")

entry_image_52 = PhotoImage(
    file=relative_to_assets("entry_52.png"))
entry_bg_52 = canvas.create_image(
    1017.5,
    569.0,
    image=entry_image_52
)
entry_52 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_52.place(
    x=940.0,
    y=552.0,
    width=155.0,
    height=32.0
)

canvas.create_text(
    819.0,
    562.0,
    anchor="nw",
    text="Date of Approval",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_rectangle(
    1107.0,
    439.0,
    1241.0,
    473.0,
    fill="#D9D9D9",
    outline="")

entry_image_53 = PhotoImage(
    file=relative_to_assets("entry_53.png"))
entry_bg_53 = canvas.create_image(
    1308.0,
    456.0,
    image=entry_image_53
)
entry_53 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_53.place(
    x=1241.0,
    y=439.0,
    width=134.0,
    height=32.0
)

canvas.create_rectangle(
    1107.0,
    483.0,
    1241.0,
    517.0,
    fill="#D9D9D9",
    outline="")

entry_image_54 = PhotoImage(
    file=relative_to_assets("entry_54.png"))
entry_bg_54 = canvas.create_image(
    1308.0,
    500.0,
    image=entry_image_54
)
entry_54 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_54.place(
    x=1241.0,
    y=483.0,
    width=134.0,
    height=32.0
)

canvas.create_text(
    1131.0,
    449.0,
    anchor="nw",
    text="Subtotal",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_text(
    1125.0,
    493.0,
    anchor="nw",
    text="Tax Rate%",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_rectangle(
    1107.0,
    517.0,
    1241.0,
    551.0,
    fill="#D9D9D9",
    outline="")

entry_image_55 = PhotoImage(
    file=relative_to_assets("entry_55.png"))
entry_bg_55 = canvas.create_image(
    1308.0,
    534.0,
    image=entry_image_55
)
entry_55 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_55.place(
    x=1241.0,
    y=517.0,
    width=134.0,
    height=32.0
)

canvas.create_text(
    1117.0,
    527.0,
    anchor="nw",
    text="Total Tax",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_rectangle(
    1107.0,
    551.0,
    1241.0,
    585.0,
    fill="#D9D9D9",
    outline="")

entry_image_56 = PhotoImage(
    file=relative_to_assets("entry_56.png"))
entry_bg_56 = canvas.create_image(
    1308.0,
    568.0,
    image=entry_image_56
)
entry_56 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_56.place(
    x=1241.0,
    y=551.0,
    width=134.0,
    height=32.0
)

canvas.create_text(
    1137.0,
    561.0,
    anchor="nw",
    text="Other",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_rectangle(
    1107.0,
    584.0,
    1241.0,
    618.0,
    fill="#D9D9D9",
    outline="")

entry_image_57 = PhotoImage(
    file=relative_to_assets("entry_57.png"))
entry_bg_57 = canvas.create_image(
    1308.0,
    601.0,
    image=entry_image_57
)
entry_57 = Entry(
    bd=0,
    bg="#F3F3F3",
    fg="#000716",
    highlightthickness=0
)
entry_57.place(
    x=1241.0,
    y=584.0,
    width=134.0,
    height=32.0
)

canvas.create_text(
    1137.0,
    594.0,
    anchor="nw",
    text="Total",
    fill="#000000",
    font=("MergeOne Regular", 11 * -1)
)

canvas.create_text(
    556.0,
    916.0,
    anchor="nw",
    text="Save",
    fill="#000000",
    font=("MergeOne Regular", 40 * -1)
)

canvas.create_text(
    756.0,
    928.0,
    anchor="nw",
    text="Export To PDF",
    fill="#000000",
    font=("MergeOne Regular", 25 * -1)
)
window.resizable(False, False)
window.mainloop()
